### ISSUE TITLE
Placing protons and neutrons in the to the nucleus

### ISSUE THREAD

**Issue by MajaVerstraeten** [ScicraftLearn/MineLabs#230]
Above the building plate is the place where the atomic nucleus is formed.

The protons and neutrons that the player adds (by clicking on the building plate) have to be added to the nucleus.

The rendering of protons and neutrons is to be determined. Options:
- Render the protons and neutrons as spheres at put them at specific coördinates (as with the Mologram) 
- Render the protons and neutrons at specific coördinates as entities that are always oriented to the player. 
- Place the protons and neutrons as blocks at coördinates that you determine. Always consider the following spherical shell and fill it up.

**Comment by JoeyDP** [comment]
It might be easier to handle the rendering of the entire atom (protons, neutrons and electrons) in one entity rather than making all of these things different entities that render themselves. A fair amount of coordination will be needed between them anyway, like is the atom stable, does it need to start a new orbital, is the atom finished, etc.
