### ISSUE TITLE
Remove LangProvider, DutchLangProvider and DutchLangProvider

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#719]
Writing jsons is easier than writing code to write jsons.

@pixar02 is there any reason to keep these?

**Comment by JoeyDP** [comment]
The same can be done for the salt generation I believe.

**Comment by pixar02** [comment]
Langs can be removed.
Was hoping it would hook into the registry of blocks/items/... And generate the keys. So we would know which we don't have.

But it's the same as the Json file.

World gen I would keep. Since we're probably going to expand on it. (Geode for salt are still wip) and with 1.20 it might change again so the gen might update the file without issues.

**Comment by JoeyDP** [comment]
Generating the keys might be interesting indeed. I saw in the interface you can add based on items rather than based son identifiers and you can also load in the existing translations from the previous file. Given these two things we should be able to generate new missing keys every time while keeping the old values AND even be able to both edit the json or run the datagen. I wouldn't put actual translations in code though.

**Comment by JoeyDP** [comment]
See #722
