### ISSUE TITLE
[Bug] LCT: When loading the world with a valid recipe in LCT, the input slots are not opened

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#767]
![image](https://github.com/ScicraftLearn/Minelabs/assets/2528391/2dcd5d59-acee-4558-a7d5-44e7ac26e226)

**Comment by pixar02** [comment]
Extra info:
Data get's saved properly on world save. And get's loaded properly (nbt data is the same before and after world load)

The real issue happens when you open the inventory for the first time after the world was closed. it overrides the synced data so the density (what we use to check for a valid recipe) is reset, 0 value.
